---
opt:
    typemap:
        numeric: <input type="number" min="0" max="2147483647">
        integer: <input type="number" min="0" max="2147483647" step="1">

tables:
    mtcars:
        tab:
            title: mtcars # The title for the tabPanel
        con: mydb # Passed through get()
        name: mtcars
        id: mtcars
        rows:
            id:
                width: 60px
                input: <input type="number" disabled>
            car:
                width: 300px
            mpg:
                width: 60px
            names:
                width: 200px
            cyl:
                width: 60px
                input: <input type="number" min="-2147483648" max="2147483647">
            disp:
                width: 60px
            hp:
                width: 60px
            drat:
                width: 60px
            wt:
                width: 60px
            qsec:
                width: 60px
            vs:
                width: 60px
            gear:
                width: 60px
            carb:
                width: 60px
            am:
                width: 60px
        keys: id